### ISSUE TITLE
Test using tifffile directly for imread/imsave

### ISSUE THREAD

**Issue by tlancon** [AiviaCommunity/PythonForAivia#11]
Allows more control over handling metadata and can fix issue with 2D+T

**Comment by tlancon** [comment]
Potential to fix #12

**Comment by tlancon** [comment]
For cases like AdjustGamma.py, skimage's imread/imsave work just fine since multiple cases don't have to be handled explicitly. It makes sense, however, to switch to using tifffile's imread/imsave for all recipes so that potential users can avoid the confusion of seeing import statements from multiple libraries for the same task. Interested in your thoughts @pmascalchi

**Comment by pmascalchi** [comment]
Indeed, tifffile read/write works as a charm and can be prioritized.
