### ISSUE TITLE
2D+T not loaded back into Aivia correctly

### ISSUE THREAD

**Issue by tlancon** [AiviaCommunity/PythonForAivia#12]
Need to specify axes using imsave

Example with skimage:
skimage.io.imsave(resultLocation, outputData, None, {'axes':'XYZ'})

Example with tifffile:
tifffile.imsave(f"{outpath}/my_TZCYX_data.tif", data, metadata={'axes': 'TZCYX'})

Do we need to say which axes are present for each case, or can we always use the TZYX format even if those aren't present?

**Comment by tlancon** [comment]
Need to test in:
- [ ] Skeletonize
- [ ] Morphological Texture
- [ ] Max Slices
- [ ] Min Slices
- [ ] Meijering Neuriteness
- [ ] Max Mask
- [ ] Adjust Sigmoid
- [ ] Adjust Gamma

**Comment by pmascalchi** [comment]
Specifying the axes for each case seems the most reproducible. Though, some scripts would use the function to write ome-xml metadata that Aivia would read fine. 
See function "create_aivia_tif_xml_metadata" in: 
https://github.com/AiviaCommunity/PythonForAivia/blob/master/Recipes/ConvertImagesForAivia/Converter_Evos.py
