### ISSUE TITLE
Typo detected in CellPose recipe

### ISSUE THREAD

**Issue by pmascalchi** [AiviaCommunity/PythonForAivia#17]
Typo is in recipe parameters definition, with type of model (**"cyto"** or nuclei), in Cellpose_Aivia.py

Related to: https://github.com/AiviaCommunity/PythonForAivia/blob/master/VenvRecipes/CellposeForAivia.md

**Comment by seismonastic** [comment]
Thanks for the info. Chi(@chichouhuang ), could you please update the typo?

**Comment by chichouhuang** [comment]
Typo fixed. Please download the latest Cellpose virtual environment fro dropbox to test.

**Comment by pmascalchi** [comment]
Perfect, thanks!
