### ISSUE TITLE
Virtualenv missing in StarDist requirements.txt

### ISSUE THREAD

**Issue by pmascalchi** [AiviaCommunity/PythonForAivia#29]
Hi Hung-Yu,

I noticed that virtualenv is used for StarDist, but the package is not installed anymore by default with Aivia installer 10.0.1+.
Since you created the script, thought it was more appropriate to let you choose the proper version requirement for this package...

https://github.com/AiviaCommunity/PythonForAivia/tree/master/VenvRecipes/StardistVenv

Thanks!

**Comment by seismonastic** [comment]
I checked-in a new version and remove the virtualenv import. I called the virtualenv.py in embedded Python in Aivia instead and it is not being used by the recipe itself.
