### ISSUE TITLE
Add API documentation to README

### ISSUE THREAD

**Issue by tlancon** [AiviaCommunity/PythonForAivia#4]
May need to branch this into its own file at some point, but for now we need to translate the example from the devs into the README

**Comment by pmascalchi** [comment]
And also specify that API doc is available in 
C:\Program Files\DRV Technologies\Aivia 8.8.2\deeplearning\
(replace version number with current one)

**Comment by pmascalchi** [comment]
This is now in:
C:\Program Files\Leica Microsystems\Aivia 14.1.0\deeplearning\

Also available in the wiki:
https://aivia-software.atlassian.net/wiki/spaces/AW/pages/550338689/Creating+Python+Recipes
