### ISSUE TITLE
Add script template and tutorial

### ISSUE THREAD

**Issue by tlancon** [AiviaCommunity/PythonForAivia#9]
Create a starting point for Aivia Python users along with a tutorial showing script creation, line by line

**Comment by pmascalchi** [comment]
Could be interesting to show here how to convert the bit depth of the output image to fit the input one.

**Comment by tlancon** [comment]
[This](https://youtu.be/mHGX4MJr3P8) tutorial covers how to use Python in Aivia.

Our Python [wiki page](https://drvision.atlassian.net/l/c/eAS6rmRw) also shows how to use Python in Aivia.

**Comment by tlancon** [comment]
@pmascalchi The original issue has stated is complete, but please comment back here if you get around to updating with a tutorial about bit depth conversion
